# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GitDaily < Formula
  desc "Extract your git activity across repos for a specific period of time."
  homepage "https://github.com/peaster/git-daily"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/peaster/git-daily/releases/download/v0.1.1/git-daily_0.1.1_darwin_amd64.tar.gz"
      sha256 "6edd4640a130a38e341e905f97fe2f629d1195c027da8ceb69ab32310bce99bf"

      define_method(:install) do
        bin.install "git-daily"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/peaster/git-daily/releases/download/v0.1.1/git-daily_0.1.1_darwin_arm64.tar.gz"
      sha256 "9b2af7f7a75d354229335e0947a316be6703226eb4ed0439b300b4a3f59951b3"

      define_method(:install) do
        bin.install "git-daily"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/peaster/git-daily/releases/download/v0.1.1/git-daily_0.1.1_linux_amd64.tar.gz"
      sha256 "37239c580c5825c869443ea4fe472b9da75820009b3cd9e4f3077dec0faeb8a8"
      define_method(:install) do
        bin.install "git-daily"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/peaster/git-daily/releases/download/v0.1.1/git-daily_0.1.1_linux_arm64.tar.gz"
      sha256 "90fae4e9421403ef866ed4823e0a027599f8356d20a3f1219210adbe0383bf2a"
      define_method(:install) do
        bin.install "git-daily"
      end
    end
  end

  test do
    system bin/"git-daily", "--help"
  end
end
