# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GitDaily < Formula
  desc "Extract your git activity across repos for a specific period of time."
  homepage "https://github.com/peaster/git-daily"
  version "0.4.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/peaster/git-daily/releases/download/v0.4.0/git-daily_0.4.0_darwin_amd64.tar.gz"
      sha256 "af76eb54d62ef07a1297d7b07966284744da27267728b8612a0cbdf9a75d3ee7"

      define_method(:install) do
        bin.install "git-daily"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/peaster/git-daily/releases/download/v0.4.0/git-daily_0.4.0_darwin_arm64.tar.gz"
      sha256 "cd6bfa264c4fe6a206cc12b57dc6deb8f59f97b222631cbe96bb5d0aad01a4d6"

      define_method(:install) do
        bin.install "git-daily"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/peaster/git-daily/releases/download/v0.4.0/git-daily_0.4.0_linux_amd64.tar.gz"
      sha256 "c538ccdc9219806be48f792e1088f50a059cf63a9db75ded1dc72ab80fbf66f8"
      define_method(:install) do
        bin.install "git-daily"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/peaster/git-daily/releases/download/v0.4.0/git-daily_0.4.0_linux_arm64.tar.gz"
      sha256 "6201b772f0cb9643856b764f1a72fa7e35ea1717ea6415a59feccc0b660bce43"
      define_method(:install) do
        bin.install "git-daily"
      end
    end
  end

  test do
    system bin/"git-daily", "--help"
  end
end
